alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - engine: PG
    name: start-agi-main
    num_nodes: 1
    size: basic-xs
    version: "12"
ingress:
  rules:
    - component:
        name: startagi-backend
      match:
        path:
          prefix: /api
name: startagi
services:
  - dockerfile_path: DockerfileRedis
    github: 
      branch: main
      deploy_on_push: true
      repo: KhulnaSoft/StartAGI
    internal_ports: 
    - 6379
    instance_count: 1
    instance_size_slug: basic-xs
    source_dir: /
    name: startagi-redis
  - dockerfile_path: Dockerfile
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        value: startagi-redis:6379
      - key: DB_URL
        scope: RUN_TIME
        value: ${start-agi-main.DATABASE_URL}
    github:
      branch: main
      deploy_on_push: true
      repo: KhulnaSoft/StartAGI
    http_port: 8001
    instance_count: 1
    instance_size_slug: basic-xs
    run_command: /app/entrypoint.sh
    source_dir: /
    name: startagi-backend
  - dockerfile_path: ./gui/DockerfileProd
    github:
      branch: main
      deploy_on_push: true
      repo: KhulnaSoft/StartAGI
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    source_dir: ./gui
    name: startagi-gui
workers:
  - dockerfile_path: Dockerfile
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        value: startagi-redis:6379
      - key: DB_URL
        scope: RUN_TIME
        value: ${start-agi-main.DATABASE_URL}
    github:
      branch: main
      deploy_on_push: true
      repo: KhulnaSoft/StartAGI
    instance_count: 1
    instance_size_slug: basic-xs
    run_command: celery -A startagi.worker worker --beat --loglevel=info
    source_dir: /
    name: startagi-celery
  
